services:
  frontend:
    image: nginx:1.27.3
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./frontend:/usr/share/nginx/js
    networks:
      - hackathon_network

  backend:
    build: ./backend  # The path to your Dockerfile
    ports:
      - "5001:5001"   # Expose port 5001 for the backend API
    depends_on:
      - db
    volumes:
      - ./backend:/app  # Mount your local backend folder to /app in the 
    #env_file:
    #  - .env
    #depends_on:
    #  - db
    networks:
      - hackathon_network

  db:
    image: mariadb:11.6.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: donnee_deploiment_si #originalement "hackathon"
    ports:
      - "3307:3307"
    volumes:
    #- db_data:/var/lib/mysql
     - ./db/donnee_deploiment_si.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - hackathon_network

volumes:
  db_data:

networks:
  hackathon_network:
    driver: bridge
