services:
  frontend:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - hackathon_network

  backend:
    build: ./backend  # The path to your Dockerfile
    ports:
      - "5001:5001"   # Expose port 5001 for the backend API
    depends_on:
      - db
    volumes:
      - ./backend:/app  # Mount your local backend folder to /app in the 
    networks:
      - hackathon_network

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hackathon
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hackathon_network

volumes:
  db_data:

networks:
  hackathon_network:
